excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://raultorrescarvajal.github.io
title: A PhD Experience
tagline: Raúl Torres
description: Notes about my life and the PhD that came with it (Raúl Torres)
paginate: 5
